[package]
name = "hematita_da_lua"
version = "0.1.0"
edition = "2018"
authors = ["Daniel Conley <himself@danii.dev>"]

[dependencies]
hashbrown = "0.11.2"
itertools = "0.10.1"

[dev-dependencies]
diff = "0.1.12"
