[package]
name = "hematita_cli"
version = "0.1.0"
edition = "2018"
authors = ["Daniel Conley <himself@danii.dev>"]

[dependencies]
hematita = {path = "../hematita"}
pico-args = {version = "0.4.2", features = ["combined-flags"]}
