name: Rust
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.4.1"
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
